balanceador:
  container_name: balanceador
  extends:
    file: balanceador/docker-compose.yml
    service: balanceador
  ports:
    - '80:80'
    - '8080:8080'
  links:
    - portal1
    - portal2
    - editor1
    - editor2
    - es1
    - es2
    - cadvisor

cadvisor:
  container_name: cadvisor
  image: google/cadvisor:latest
  privileged: true
  volumes:
    - '/:/rootfs:ro'
    - '/var/run:/var/run:rw'
    - '/sys:/sys:ro'
    - '/var/lib/docker/:/var/lib/docker:ro'
  expose:
    - '8080'

portal1:
  container_name: portal1
  extends:
    file: portal-de-servicos/docker-compose.yml
    service: portal-de-servicos
  links:
    - es1
    - es2

portal2:
  container_name: portal2
  extends:
    file: portal-de-servicos/docker-compose.yml
    service: portal-de-servicos
  links:
    - es1
    - es2
  environment:
    FLAGS_IMPORTAR_AUTOMATICAMENTE: false

editor1:
  container_name: editor1
  extends:
    file: editor-de-servicos/docker-compose.yml
    service: editor-de-servicos

editor2:
  container_name: editor2
  extends:
    file: editor-de-servicos/docker-compose.yml
    service: editor-de-servicos

es1:
  container_name: es1
  image: elasticsearch
  links:
   - es2

es2:
  container_name: es2
  image: elasticsearch
