balanceador:
  image: servicosgovbr/balanceador
  ports:
    - '80:80'
  links:
    - portal1
    - portal2
    - editor1
    - editor2
    - es1
    - es2

portal1:
  extends:
    file: portal-de-servicos/docker-compose.yml
    service: portal-de-servicos
  links:
    - es1
    - es2

portal2:
  extends:
    file: portal-de-servicos/docker-compose.yml
    service: portal-de-servicos
  links:
    - es1
    - es2
  environment:
    FLAGS_IMPORTAR_AUTOMATICAMENTE: false

editor1:
  extends:
    file: editor-de-servicos/docker-compose.yml
    service: editor-de-servicos

editor2:
  extends:
    file: editor-de-servicos/docker-compose.yml
    service: editor-de-servicos

es1:
  image: elasticsearch
  links:
   - es2

es2:
  image: elasticsearch
